### ISSUE TITLE
Sending nested JSON

### ISSUE THREAD

**Issue by wildfiregt** [jaksab/EasyNetwork#10]
So far the only way i found to send a json is to add parameters one by one
The method .setBody(body) doesn't seem to do anything.
If I want to send a post or a put with nested json ,say i have this class 

User {
 int userId;
 String userName;
 City city;
}
City {
 int cityId;
 String cityName;
}

And my REST controller expect a JSON of type : 
{
  "userId": 1,
  "name": "Name",
  "city": {
    "cityId": 1,
    "cityName": "City1"
  }
}

How can I post/put this in the body ?

**Comment by wildfiregt** [comment]
So I checked the code, it seems that EasyNet.setBody(String body) leads to makeRequestBody(HttpURLConnection connection) in JSONTask class. However it never uses the requestModel.getBody(). Instead it writes the params. Why is that ?
Using setRawBody(connection,requestModel.getBody()); in makeRequestBody accomplished what I wanted. 
But why there's no way of setting the body ?

**Comment by jaksab** [comment]
Hello!
Use .setContentType(NConst.MIME_TYPE_JSON)
And body automatically will be makes to json format if you will use addParam method; If you want send model, then you can use Gson and put body to request;

**Comment by wildfiregt** [comment]
That's the issue ,it even if you set content type to NConst.MIME_TYPE_JSON. The body is still empty
Here's the code i used ,and the logs i got 
![logs](https://user-images.githubusercontent.com/17387206/39087909-52ffe2b4-45a0-11e8-8791-a7d05e71fec5.jpg)

**Comment by jaksab** [comment]
Understood, I will fix in the near future

**Comment by jaksab** [comment]
Completed, test please
