### ISSUE TITLE
Access background thread

### ISSUE THREAD

**Issue by wildfiregt** [jaksab/EasyNetwork#11]
Is there a way to write codes in the doInBackground method of the Asynctask ?
All the overrided methods happens on the main UI thread.
What I want is sleep the backgruond thread for atleast 1 sec so that the progress dialog doesn't show and hide too quickly
Thanks

**Comment by jaksab** [comment]
Hi. 
I have already prepared a delay for progress view displaying.
User method .bind(ProgressView view) in Request. 
There are still overloads to hide the content at the time of the request, etc.
To make an artificially delayed flow in 1 second would be very bad, I realized on the handler.

But if you want do other custom tasks in background thread after your request is completed, You can overide public boolean finish(NResponseModel responseModel)  in your NCallback realization. But do not forget to call the super class method if you use parsing via Gson (NCallbackGson or NCallbackParse) realizations.
