### ISSUE TITLE
Retry a request after it fails

### ISSUE THREAD

**Issue by rokhsat** [jaksab/EasyNetwork#12]
Hi
What i'm seeking is to override addOnErrorDefaultListener and resend the request with all its parameters after it fails (cause of bad network for example)
Is there a way to do it without having to catch these events on every requests of every activity ?

**Comment by jaksab** [comment]
@rokhsat Hi!
When you create request (call get, post etc), EasyNet returns an instance of the Resuest class. Save it and you will be able to use it again in the onFailed method.
