### ISSUE TITLE
Url encoding for query parameters is incorrect in version 1.2.6 and up

### ISSUE THREAD

**Issue by killvetrov** [jaksab/EasyNetwork#8]
Проблемный коммит: b3f122e7b4b0ea6f27235a432ba09af3a02b0ad7

Поведение в предыдущих версиях:
`[Query params]: q=Luke+Bryan++Brett+Eldredge+%26+Granger+Smith+Klipsch+Music+Center; imageType=photo; mkt=en-us; offset=0; count=4`

Поведение в версии 1.2.6 и выше:
`[Query params]: q=Dallas Cowboys vs. Green Bay Packers AT; T Stadium; imageType=photo; mkt=en-us; offset=0; count=4`

**Comment by jaksab** [comment]
@killvetrov Please, check version 1.3.0

**Comment by killvetrov** [comment]
Confirm this bug is fixed in 1.3.0.
